### ISSUE TITLE
Consider how to draw first parties that are also third parties

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/lightbeam-we#110]
For example: www.google.com is a first party site, but is also a third party site for www.youtube.com. If you visit www.google.com and then www.youtube.com, the google first party node disappears in the visualization currently, because the `www.google.com` website object gets assigned an `isVisible` key with a value of `false` once is it linked as a third party by www.youtube.com.

When a website object has an `isVisible` key set to `false`, it is ignored by the `getAll` method currently, and likely also by the per-website updates, but this should be confirmed.

In general, we should consider how these types of sites, that are both first and third parties, are handled and show up in the visualization in both the case of a page refresh (a call to `store.getAll`) and an update (`store.updateChild`) inside `store.setFirstParty` and `store.setThirdParty`.

@jonathanKingston I am guessing this is P1, but please update the priority flag as you deem appropriate!

**Comment by biancadanforth** [comment]
@jonathanKingston Found another symptom of this bug:

![firstpartiesalsothirdpartiesbug](https://user-images.githubusercontent.com/17437436/28724231-2c9e0786-736e-11e7-8f76-8bc8a78c06df.png)

**What we believe is happening:**
* A first party site (Site A) is initially drawn as expected to the visualization, linking to a third party, Site B.
* Later, another website (Site C) links to Site A as a third party, and in this case Site A is overwritten as a third party and is whitelisted.
* This gives Site A an `isVisible` key set to `false`
* When the visualization gets updated, Site A gets removed from the graph, but the third party, Site B that it originally linked to remains, without the link.

**Comment by biancadanforth** [comment]
@jonathanKingston Can you provide more details about how this could be tested? You had mentioned something about local servers in our weekly meeting which I didn't follow...

My thought:
Just as we have an allowlist override for third parties owned by first parties, perhaps we have an allowlist override override if that third party is already in storage listed as a first party?

I.e. for Google.com, if it is already drawn on the visualization as a first party and is then linked to as a third party, just leave it alone (don't make its `isVisible` key `false`) and add the new link.

**Comment by jonathanKingston** [comment]
> for Google.com, if it is already drawn on the visualization as a first party and is then linked to as a third party

This is clear for google.com however more obscure sites would need to be elevated from being a third party to being a first party. Treating them consistently to appear as a first party would be the correct behavior here.
I agree that how current lightbeam does this is what we want also.

**Comment by jonathanKingston** [comment]
Visit:
- https://www.google.com/search?q=dfdfdf&ie=utf-8&oe=utf-8&client=firefox-b-ab
- https://www.youtube.com/
- https://developers.google.com/youtube/youtube_player_demo

This first looks like this:
![image](https://user-images.githubusercontent.com/338988/29791517-0ec31692-8bf2-11e7-8e86-a7d75256d952.png)

The left triangles are s.ytimg.com,  i.ytimg.com the top triangle is google-developers.appspot.com

On refresh:
![image](https://user-images.githubusercontent.com/338988/29791616-6b0e9d68-8bf2-11e7-8a09-4d0a0f7f59a1.png)


Which means we are missing links to ytimg.com to youtube.com somehow.

**Comment by jonathanKingston** [comment]
I was also seeing the above steps remove all links which is super odd (brand new computer, this is the first thing I checked) resetting the database made it work, we should perhaps check that the database is in the right more after installing.

**Comment by jonathanKingston** [comment]
JSON dump of the above flow:

```
{
  "developers.google.com": {
    "hostname": "developers.google.com",
    "favicon": "https://developers.google.com/_static/66ebbcad58/images/favicon.png",
    "firstPartyHostnames": false,
    "firstParty": true,
    "thirdParties": [
      "google-developers.appspot.com",
      "www.google.com",
      "www.youtube.com",
      "s.ytimg.com",
      "i.ytimg.com"
    ]
  },
  "google-developers.appspot.com": {
    "hostname": "google-developers.appspot.com",
    "favicon": "",
    "firstPartyHostnames": [
      "developers.google.com"
    ],
    "firstParty": false,
    "thirdParties": []
  },
  "i.ytimg.com": {
    "hostname": "i.ytimg.com",
    "favicon": "",
    "firstPartyHostnames": [
      "www.youtube.com",
      "developers.google.com"
    ],
    "firstParty": false,
    "thirdParties": []
  },
  "s.ytimg.com": {
    "hostname": "s.ytimg.com",
    "favicon": "",
    "firstPartyHostnames": [
      "www.youtube.com",
      "developers.google.com"
    ],
    "firstParty": false,
    "thirdParties": []
  },
  "www.google.com": {
    "hostname": "www.google.com",
    "favicon": "https://www.google.com/images/branding/product/ico/googleg_lodp.ico",
    "firstPartyHostnames": [
      "www.youtube.com",
      "developers.google.com"
    ],
    "firstParty": false,
    "thirdParties": []
  },
  "www.youtube.com": {
    "hostname": "www.youtube.com",
    "favicon": "https://www.youtube.com/yts/img/favicon_144-vflWmzoXw.png",
    "firstPartyHostnames": [
      "developers.google.com"
    ],
    "firstParty": false,
    "thirdParties": []
  }
}
```

**Comment by jonathanKingston** [comment]
Youtube.com isn't marked as a first party that is an issue.

**Comment by biancadanforth** [comment]
I see what you are seeing on my branch, for the following sequence:

1. https://www.google.com/search?q=dfdfdf&ie=utf-8&oe=utf-8&client=firefox-b-ab
2. https://www.youtube.com/
3. https://developers.google.com/youtube/youtube_player_demo

but more immediately, I see on the `master` branch that a bunch of what should be allowlisted (and therefore hidden) third parties to youtube are showing up on the visualization.

![screen shot 2017-08-28 at 9 09 18 pm](https://user-images.githubusercontent.com/17437436/29804068-dda26db8-8c34-11e7-9511-2a5c96e52450.png)

I know that youtube should only have two third party nodes after the whitelist: `s.ytimg.com` and `i.ytimg.com`, yet above it has connections to three allowlisted third parties:
- doubleclick.net
- googlesyndication.com
- 2mdn.net

When I inspect youtube in storage, I see that it has a `firstParty` of `true` and an `isVisible` of `false`. Based on current logic, this means youtube was first an allowlisted third party for another site, and then became a first party. I plan to fix this symptom first and see how that affects what we see for this sequence of sites, and then go from there.

Ensuring these allowlisted third parties don't make it onto the visualization when it is updated will ensure they don't show up as detached triangles on page reload, which is what is happening right now in the master branch:

![screen shot 2017-08-28 at 9 19 47 pm](https://user-images.githubusercontent.com/17437436/29804212-f63d3a0a-8c35-11e7-944a-7f0785287509.png)

I'm too tired to figure this out tonight; but I will look at it with fresh eyes tomorrow morning.

**Comment by jonathanKingston** [comment]
I would consider making that a different issue in that some allow lists get onto the graph.

**Comment by jonathanKingston** [comment]
Should be fixed with latest patch.
