### ISSUE TITLE
Animations on the graph

### ISSUE THREAD

**Issue by princiya** [mozilla/lightbeam-we#124]
Good to have some animations on the graph to match the current version.

**Comment by biancadanforth** [comment]
The low frame rate makes the graph look like it's twitching back to force equilibrium. This could be also related to #123 . Here's a gif that shows the twitching when I:
* drag and then pan
* drag and then zoom

![drag-pan-zoom-twitching](https://user-images.githubusercontent.com/17437436/29130405-8ee2becc-7cde-11e7-8629-5c79b5131ac1.gif)

**Comment by princiya** [comment]
@biancadanforth what do you think about this issue? is it addressed in PR #158? If so, please close this one :). Thanks.

**Comment by biancadanforth** [comment]
Yep it's much better; thanks @princiya! Though I don't have issue-closing powers...

**Comment by princiya** [comment]
Thanks @biancadanforth !
