### ISSUE TITLE
Consider what UI features to add/remove

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/lightbeam-we#129]
There are several features of the legacy Lightbeam that we have not implemented, for example:
* Site Info
* List View
* Tracking Protection
* Toggle Controls
* Save Data
... and others.

For any UI features not implemented, we should omit them from the UI (as opposed to disabling them) and create a separate issue in GitHub of the form: Consider adding X from legacy Lightbeam.

![screen shot 2017-08-08 at 9 17 42 am](https://user-images.githubusercontent.com/17437436/29082283-e84e4f82-7c19-11e7-92f6-d86e2c654266.png)

**Comment by princiya** [comment]
@biancadanforth can we close this issue because of #139?

**Comment by biancadanforth** [comment]
@princiya Yeah I think that's a good call. We have separate issues for implementing the other main features already. I can close this one myself!
