### ISSUE TITLE
Create an updated gif for the Readme

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/lightbeam-we#132]
Now we have progressed a lot it would be great to see a nightly gif here of the latest view.

**Comment by maqboolkhan** [comment]
Hi do we need a GIF on how to use lightbeam ? i want to work on it kindly guide me 🙂

**Comment by jonathanKingston** [comment]
The prior gif was just an animated version of the current README image. Feel free to add one and change the README.md via github to have that path.

Let me know if you need more info, a program like LICEcap can do gif making.

**Comment by maqboolkhan** [comment]
Thanks m on it but what would be our GIF motivation? are we going to show lightbeam usage or something else?

**Comment by jonathanKingston** [comment]
Just to show what the graph does and how it looks before using it. We don't need anything fancy here, just the graph moving a little to make it look a little interesting. No need to view other sites or interact with the graph.

**Comment by maqboolkhan** [comment]
cool awesome ill do it

**Comment by maqboolkhan** [comment]
Hi @jonathanKingston i have raised a PR https://github.com/mozilla/lightbeam-we/pull/229 kindly check

**Comment by jonathanKingston** [comment]
Great thanks @maqboolkhan!
