### ISSUE TITLE
Set up a place for feedback and update 'Give Us Feedback' link in UI

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/lightbeam-we#140]
The legacy Lightbeam links to `lightbeam-feedback@mozilla.org`. Since it has been several years since this was set up, we should consider where to send users (here or otherwise) if they have feedback and update the link in the UI accordingly.

One idea is to create a Lightbeam topic on [Discourse](https://discourse.mozilla.org/
). For example [Containers](https://discourse.mozilla.org/c/test-pilot/containers) has its own discusson area within Test Pilot. This could also be referenced in the `CONTRIBUTORS.md` file as the first point of contact until this repo is moved to Mozilla and/or other communication channels open up.

**Comment by biancadanforth** [comment]
I talked to Caitlin Neiman on the Add-On's team, and she suggested the best place would be a thread on Discourse > Add-ons > Contribute > Lightbeam and use the URL there for the Feedback link and Contributors.md document.

Also she recommended Princiya and I join the [Mozillians](https://mozillians.org/en-US/) network, which gives us better access to Mozilla resources (like Air Mozilla, Discourse, etc.) as a community member post-internship. @princiya I encourage you to sign up; you will then be given a link to give to a Mozillian to vouch for you (this could be Jonathan for example). Per Caitlin, if we get three people to vouch for us, we have access to the most Mozilla resources as a non-employee.

**Comment by jonathanKingston** [comment]
As an update I asked for a discourse category to be made for us.
