### ISSUE TITLE
Plan for the end of internship!

### ISSUE THREAD

**Issue by princiya** [mozilla/lightbeam-we#145]
It's been a great journey so far with **_Outreachy - Lightbeam - Mozilla_**. Both, I and @biancadanforth have learned lots! While the two of us intend to keep contributing post-internship, let's use this space to create a wrap-up plan so that we are all aligned for the _official_ last 2.5 weeks of this internship.

@biancadanforth  @jonathanKingston @arroway @pauljt @groovecoder Please add your inputs :)

**Comment by biancadanforth** [comment]
Thanks @princiya for trying to centralize thinking around this. Great idea.

To the extent that some of these bullets could be (or currently are) represented by issues on the repo, I think it'd be great if we could reference them in your list, so those discussions can be tracked more closely. For example, we have issues for the CoC and Contributing docs, and some issues that are related to Community building (

Also I saw you had made a checklist a couple of times in Markdown which seems very helpful -- perhaps the bullets could be converted into checkmarks, so we could use this issue to track overall progress over the next two weeks?

**Comment by princiya** [comment]
**The plan**

- [ ] Fix P1 issues
- [ ] Fix P2 issues (based on time & availability)
- [ ] Readme, CoC, Contributing docs
- [ ] QA/Testing
- [ ] Collect feedback
- [ ] Publish

Items | Issue | PR
--- | --- | ---
P1 - Draw first parties which are also third parties | #110 | --- 
P1 - Dynamic vars | #65 | ---
P2 - Improve graph forces | #123 | ---
P2 - Graph animations | #124 | ---
P2 - Graph filters | #130 | ---
P2 - Improve UI | #146 | ---
Readme, CoC, Contributing docs | #127 | #138 
Setup feedback place | #140 | ---
Setup testing for non-devs (& get feedback) | #141 | ---

**Next steps**
   - [ ] [Mozilla Open Leader Program](https://medium.com/read-write-participate/work-in-the-open-with-mozilla-1410be0a83b2) This program will cover the following:
       - Staying involved
       - Community building
       - Project communication / maintenance

**Comment by princiya** [comment]
**Next steps**
   - [ ] [Mozilla Open Leader Program](https://medium.com/read-write-participate/work-in-the-open-with-mozilla-1410be0a83b2) This program will cover the following:
       - Staying involved
       - Community building
       - Project communication / maintenance

**Comment by jonathanKingston** [comment]
Closing this as the internship has ended 😢 

We should be launching in a week or so whenever makes sense, perhaps with more fixes to solve a few more issues.

**Comment by princiya** [comment]
No longer access to slack :( @jonathanKingston where do we talk? :)

**Comment by jonathanKingston** [comment]
IRC, email perhaps? Drop me an email and we could discuss.

**Comment by groovecoder** [comment]
For anyone following here outside email, I suggest #privacy and #lightbeam on IRC?

**Comment by princiya** [comment]
sure @groovecoder 👍
