### ISSUE TITLE
Increase graph size

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/lightbeam-we#146]
There are some areas where `display: grid` is used where it makes more sense to use `display: flex`.

For example, we use `display: grid` for the `main` element, which results in uneven whitespace at the bottom of the element, since we give the footer a row-height of 30%:

![screen shot 2017-08-16 at 8 28 29 am](https://user-images.githubusercontent.com/17437436/29374793-8d987866-8267-11e7-8d8c-b7f97d270a1c.png)

If we use `display: flex`, we can use `flex-direction: column` and `justify-content: space-between` to push the footer all the way to the bottom and widen the visualization area:

![screen shot 2017-08-16 at 8 31 07 am](https://user-images.githubusercontent.com/17437436/29374850-c143c36e-8267-11e7-9f64-a73e1cc77380.png)

Converting main to display flex will also ensure the headers in main don't take up more space than they need to:

![screen shot 2017-08-16 at 8 50 10 am](https://user-images.githubusercontent.com/17437436/29374908-f61dac62-8267-11e7-8c24-d4d1bcd5f8c1.png)

In general, relative sizes using `display: grid` (ex: % or fr) mean that we are specifying a width or height of an element based on the height of its parent or the height of the window -- independent of its actual content/padding. What we really want is to say: place it as far down (for the footer) or as far up (for the graph headers) the page as possible given its size, and let the middle flex item (the visualization div) grow to meet them. This is where flexbox comes in handy.

There may be other areas too where the UI could be tweaked; this issue should encompass all of those nits.

**Comment by princiya** [comment]
This is a nice example of where grid works vs doesn't! Thanks @biancadanforth for summing it up so well.

**Comment by jonathanKingston** [comment]
The graph should actually appear underneath all these other elements. I'm not bothered on solution.

One solution could be setting the graph as 100vh and lay over the top.
