### ISSUE TITLE
Disconnected third parties on the graph

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/lightbeam-we#150]
In @biancadanforth's patch I am still seeing nodes that are triangle and disconnected from any other node, this should never happen.

**Comment by biancadanforth** [comment]
This may be a symptom of #110 .

**Comment by jonathanKingston** [comment]
Nah it's something else, probably a bug in capture.

I just got it with your patch for ssl.gstatic.com when just loading getpocket.com

I got a request to:
https://ssl.gstatic.com/accounts/o/971028622-postmessagerelay.js

This is actually a blocker.
