### ISSUE TITLE
Some allowlist third parties show up on the graph

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/lightbeam-we#179]
See [this comment](https://github.com/mozilla/lightbeam-we/issues/110#issuecomment-325550561) for an explanation.

I believe this is a related issue to #110 .

**Comment by biancadanforth** [comment]
Basically, `youtube` starts out as a first party, and later becomes an allowlisted third party (so that it's `firstParty` key is set to `false` and `isVisible` key is also set to `false`). This means when we refresh the page, `getAll`, which only returns nodes that are either `firstParty` or `isVisible` `true`, ignores `youtube`, so any nodes it was originally connected to in the visualization lose their `youtube` link.

In general, the logic of `setThirdParty` should be such that `firstParty` and `isVisible` should **never** be changed if they are ever `true`.

**Comment by jonathanKingston** [comment]
Should be fixed with latest patch.
