### ISSUE TITLE
Add button in First Run page to open Lightbeam tab

### ISSUE THREAD

**Issue by biancadanforth** [mozilla/lightbeam-we#190]
PR #186 is a good basic set up for Lightbeam's first run page (`first-run.html`), but it would be helpful to add a button on this page to make it easier for users to open the Lightbeam page (`index.html`) for the first time.

**Comment by maqboolkhan** [comment]
hi i want to work on it kindly guide me what is the requirement as i could not understand properly
Thanks

**Comment by jonathanKingston** [comment]
There is already a PR outstanding for this work, I think we are good here. I just haven't checked it over yet.

**Comment by maqboolkhan** [comment]
ok thanks
