### ISSUE TITLE
CSS for the reset data dialog box

### ISSUE THREAD

**Issue by princiya** [mozilla/lightbeam-we#198]
![Screenshot](https://user-images.githubusercontent.com/338988/29068071-1d5f646e-7c2d-11e7-9a72-65ebd296e066.png)

Implement CSS for the reset data dialog box as above.

**Comment by andrewhayward** [comment]
Assuming nobody else has picked this up, I'll claim it. @princiya, do you have colour codes, font sizes, or other specifications? Or shall I just make a best guess? And is there an original graphic anywhere for the dialog icon?

**Comment by princiya** [comment]
You could refer style.css for the existing specifications. We only have
this screenshot for reference. Thanks for considering this issue 😊

On 5 Oct 2017 09:15, "Andrew Hayward" <notifications@github.com> wrote:

Assuming nobody else has picked this up, I'll claim it. @princiya
<https://github.com/princiya>, do you have colour codes, font sizes, or
other specifications? Or shall I just make a best guess? And is there an
original graphic anywhere for the dialog icon?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/lightbeam-we/issues/198#issuecomment-334350841>,
or mute the thread

**Comment by jonathanKingston** [comment]
The previous code is in the old repo: https://github.com/mozilla/lightbeam

If you could look at that and move it into the same style as we have here that would be great.
