### ISSUE TITLE
Meaningful variable names for the reset data dialog box message

### ISSUE THREAD

**Issue by princiya** [mozilla/lightbeam-we#199]
PR #197 added a warning message before resetting data.

As per the follow-up comment in that PR, we need to have meaningful variable names for the reset data message.

> Changing to meaningful variable names (rather than start and end)
Do the concat in the template string (rather than having spaces in the strings):
${msgDeletion} ${msgConfirm}

Template for the message:

![Image](https://user-images.githubusercontent.com/338988/29068071-1d5f646e-7c2d-11e7-9a72-65ebd296e066.png)

**Comment by maqboolkhan** [comment]
hi is there any one working on it i want to work on it? if no one working on it im up for this

**Comment by princiya** [comment]
@maqboolkhan you could take this up.

**Comment by maqboolkhan** [comment]
ok i am up for this will do it

**Comment by maqboolkhan** [comment]
hi @princiya @jasonthomas i am sorry but i am unable to find PR #197 code (changes) in master branch

**Comment by princiya** [comment]
Sorry @maqboolkhan This has been already fixed in PR #221 [here](https://github.com/mozilla/lightbeam-we/blob/master/src/index.html#L141)
