### ISSUE TITLE
Dexie errors

### ISSUE THREAD

**Issue by princiya** [mozilla/lightbeam-we#200]
@jonathanKingston I have the following errors from dexie.js. Any inputs or am I missing anything?

![screen shot 2017-09-07 at 19 57 13](https://user-images.githubusercontent.com/8022693/30177645-c673d652-9406-11e7-9133-28bb1bf37032.png)

![screen shot 2017-09-07 at 19 57 31](https://user-images.githubusercontent.com/8022693/30177662-d1cbff16-9406-11e7-9e71-7d450a57b74e.png)

**Comment by jonathanKingston** [comment]
@princiya said this was not an issue now.

**Comment by princiya** [comment]
works via the `web-ext` command. I always try via `about:debugging` and it seemed erroneous.
