### ISSUE TITLE
[Bug] Missing Page Content

### ISSUE THREAD

**Issue by zero77** [mozilla/lightbeam-we#213]
I am missing the bottom and right side page content also, clicking on graph view doesn’t do anything.
Thanks

What I am getting:
![capture](https://user-images.githubusercontent.com/16563034/31045561-2913ce1e-a5de-11e7-8950-b9eb01b56166.JPG)

What I should be getting:
![capture](https://addons.cdn.mozilla.net/user-media/previews/full/116/116420.png?modified=1416948686)

**Comment by jonathanKingston** [comment]
Lightbeam has been migrated to a new version read about that here:

https://github.com/mozilla/lightbeam-we/wiki/Migration-from-1.x-Lightbeam

I think this makes most sense to break into smaller bugs.

Like #79 or #130 cover two of the core areas you mention.

I think if there are specific priorities, upvote and raise those specifically.

Thanks!
