### ISSUE TITLE
Tracking protection on restart is reset

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/lightbeam-we#216]
We have had a few users report that on restart of the browser tracking protection has been reset.
This should be investigated immediately.

**Comment by princiya** [comment]
@jonathanKingston are there any specific pointers to look at this tracking protection bug? I don't have much insights about this tracking protection.

**Comment by jonathanKingston** [comment]
TBH I think it's unsupported in 56 which is where the issue is coming from perhaps. Either that or it's the initial state of the button isn't always initialised correctly.
