### ISSUE TITLE
Lightbeam's Tracking Protection switch does not work

### ISSUE THREAD

**Issue by cpeterso** [mozilla/lightbeam-we#224]
Lightbeam's Tracking Protection switch does not reflect the current state of the Tracking Protection preference and toggling the switch does not update the preference. I am using Firefox Nightly 58.0a1 and Lightbeam 2.0.3.

I see the following JS error message in the devtools console:
```
ReferenceError: can't access lexical declaration `trackingProtection' before initialization
lightbeam.js:23:7
```

**Comment by jonathanKingston** [comment]
@pauljt fixed this today, making a release now.

**Comment by cpeterso** [comment]
Thanks! I confirmed that the switch now works correctly in Lightbeam 2.0.4.

**Comment by jonathanKingston** [comment]
Cool thanks for confirming!
