### ISSUE TITLE
lightbeam working not correctly as before. What can I do ?

### ISSUE THREAD

**Issue by Monzfan** [mozilla/lightbeam-we#236]
Hello together: 
I was happy to use lightbeam again on firefox 57. But I realize that it works only on "light version" or so:
Normally it works like your description on wikipedia link and attached picture. 
https://de.wikipedia.org/wiki/Lightbeam

At the moment ligthbeam works not in full version ors so.
No lists, no chance to switch of third party. Only picture which shows visited sites and third party.
Nothing with blocking third party...

What can I do t use it like you describe in https://de.wikipedia.org/wiki/Lightbeam?

**Comment by Monzfan** [comment]
At the moment working:
![lightbeam](https://user-images.githubusercontent.com/33925309/33513570-71235074-d745-11e7-8dc8-8a1b9e854338.JPG)

Should work like:
![lightbeameee](https://user-images.githubusercontent.com/33925309/33513576-93b33578-d745-11e7-9e49-21bb5ff0156c.JPG)

**Comment by princiya** [comment]
Hi @Monzfan,

Thank you for using Lightbeam.

At the moment, we only have the 'light version'. You can find a report of the missing features [here](https://github.com/mozilla/lightbeam-we/wiki/Migration-from-1.x-Lightbeam#missing-features).

We plan to add them soon to Lightbeam as and when we get resources and time. Meanwhile, if you are a developer and interested to contribute, we are happy to have PRs :)
