### ISSUE TITLE
Use consistent braces for arrow functions

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/lightbeam-we#64]
From #62

> Please add a follow up bug to make this use braces. Having the implied return may in future cause issues as this method returns a promise...blocking requests for example would delay.

```
(response) => this.sendThirdParty(response),
```

IF you can find an Eslint rule that would be great too.

**Comment by epq** [comment]
Hi, I'd like to work on this issue! For clarification, this PR is for fixing braces throughout the entire project, not just the line from #62 (which doesn't appear to be an issue anymore)?

Is [arrow-body-style: always](https://eslint.org/docs/rules/arrow-body-style) the ESLint rule you are looking for?

**Comment by jonathanKingston** [comment]
@epq looks like the right rule yeah and it would need to be checked for all non library code that we import. Thanks!

**Comment by jonathanKingston** [comment]
Please let me know if you have other questions etc. Remember to add "Fixes #64" in your commit message like other commits in this repo :).
Thanks
