### ISSUE TITLE
Fix toggle button to work in CSS

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/lightbeam-we#66]
Remove the hard coding of "off" and use CSS to control the toggle button.

The functionality of this button can be done elsewhere.

**Comment by jonathanKingston** [comment]
**Note** the functionality itself depends on a web extension API that doesn't exist yet. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1345158

**Comment by laxmy** [comment]
Hi Lightbeam Team,
I'm interested in working/contributing on this project. 
This looks like something I can take up. Is this up for grabs?

**Comment by jonathanKingston** [comment]
@laxmy the initial work here is to duplicate a toggle that is available for the current Lightbeam (top right of the page) using CSS and semantic markup as much as possible (so using a native checkbox and style correclty based on `:checked` status etc)

The timescale is a little tight here so we might have to step in if we need to go faster, however yeah we can take patches for any "good first bug".

I'm going to assign this to you for the time being. Shout if you have questions etc.

@biancadanforth as a heads up this is off your plate however when you get time from p1's this could use the backend to actually enable the tracking protection toggle.

**Comment by biancadanforth** [comment]
@laxmy Thanks for you interest in helping out! We already have some HTML/CSS for this toggle, the markup is copied below. You can view the toggle by removing the `unimplemented` class on the `div.tracking-protection` element. Feel free to use this as a point of departure and reference regarding the color scheme.

```html
<!-- @todo add tracking protection and toggle functionality -->
  <div class="tracking-protection unimplemented">
    <label for="tracking-protection-control">Tracking Protection</label>
    <div class="toggle-switch">
      <!-- @todo couple checkbox status (checked/unchecked) with toggle status -->
      <input type="checkbox" id="tracking-protection-control">
      <span class="toggle"></span>
      <!-- @todo toggle-switch text (off/on) to reflect state of tracking protection -->
      <span class="toggle-status">Off</span>
  </div>
</div>
```

**Comment by jonathanKingston** [comment]
Ideally it won't need toggle or toggle status and could be done with CSS `::before` and `::after` instead but it may not be workable.

**Comment by laxmy** [comment]
@jonathanKingston and @biancadanforth ....Thanks for the info and the starting point. I'm working on this. The alert window that shows info about tracking protection will be enabled from the back-end is my understanding.

**Comment by jonathanKingston** [comment]
This is fixed by the latest merge from @laxmy thanks again.
